name: android
description: "Women Safety App"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  permission_handler: ^11.4.0
  geolocator: ^12.0.0
  sensors_plus: ^5.0.1
  vibration: ^3.1.3
  hardware_button_listener: ^0.0.1
  speech_to_text: ^7.3.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  flutter_background_service: ^5.0.0
  flutter_background_service_android: ^6.2.2
  flutter_background_service_ios: ^5.0.0
  firebase_core: ^2.30.1
  firebase_database: ^10.5.3
  contacts_service: ^0.8.0   # fixed for Flutter 3.35.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
